require 'bundler/setup'

ENV['RACK_ENV'] ||= 'development'
Bundler.require(:default, ENV['RACK_ENV'])

require 'praxis/tasks'

desc "Drop into a console with the full application loaded"
task console: 'praxis:console'

require 'rspec/core/rake_task'
RSpec::Core::RakeTask.new(:spec)

Dir["lib/tasks/**/*.rake"].each { |ext| load ext }

task :default => :spec
